# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/css/images/'),
            preserve_default=False,
        ),
    ]
