# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(upload_to='blog/static/css/images/'),
        ),
    ]
