# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170226_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(upload_to='static/css/images/'),
        ),
    ]
