# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformcategory',
            options={'base_manager_name': '_plain_manager'},
        ),
        migrations.AlterModelOptions(
            name='contactformcategorytranslation',
            options={'default_permissions': (), 'managed': True},
        ),
        migrations.AlterModelManagers(
            name='contactformcategory',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='contactformcategorytranslation',
            name='master',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='contact_form.ContactFormCategory'),
        ),
    ]
